FROM node:alpine

LABEL maintainer="zjc"

# install cnpm & vue tools
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org && \
 	cnpm install -g @vue/cli && \
 	cnpm install -g @vue/cli-service-global
